import { CloseCashRegisterHandler } from '@/data/handlers/financial/close-cash-register-handler';
import { CreateCashMovementHandler } from '@/data/handlers/financial/create-cash-movement-handler';
import { CreateFinancialEntryHandler } from '@/data/handlers/financial/create-financial-entry-handler';
import { CreatePayableHandler } from '@/data/handlers/financial/create-payable-handler';
import { GetCashFlowHandler } from '@/data/handlers/financial/get-cash-flow-handler';
import { GetCurrentCashRegisterHandler } from '@/data/handlers/financial/get-current-cash-register-handler';
import { GetFinancialDashboardHandler } from '@/data/handlers/financial/get-financial-dashboard-handler';
import { GetSalesTotalHandler } from '@/data/handlers/financial/get-sales-total-handler';
import { OpenCashRegisterHandler } from '@/data/handlers/financial/open-cash-register-handler';
import { PayPayableHandler } from '@/data/handlers/financial/pay-payable-handler';
import { SearchCashRegisterHistoryHandler } from '@/data/handlers/financial/search-cash-register-history-handler';
import { SearchFinancialCategoryHandler } from '@/data/handlers/financial/search-financial-category-handler';
import { SearchPayableHandler } from '@/data/handlers/financial/search-payable-handler';
import { SearchReceivableHandler } from '@/data/handlers/financial/search-receivable-handler';
import { SettleReceivableHandler } from '@/data/handlers/financial/settle-receivable-handler';
import { httpClient } from '@/main/factories/http/make-http-client';

export const makeGetFinancialDashboard = () => new GetFinancialDashboardHandler(httpClient);
export const makeGetSalesTotal = () => new GetSalesTotalHandler(httpClient);
export const makeGetCurrentCashRegister = () => new GetCurrentCashRegisterHandler(httpClient);
export const makeSearchCashRegisterHistory = () => new SearchCashRegisterHistoryHandler(httpClient);
export const makeOpenCashRegister = () => new OpenCashRegisterHandler(httpClient);
export const makeCreateCashMovement = () => new CreateCashMovementHandler(httpClient);
export const makeCloseCashRegister = () => new CloseCashRegisterHandler(httpClient);
export const makeSearchReceivable = () => new SearchReceivableHandler(httpClient);
export const makeSettleReceivable = () => new SettleReceivableHandler(httpClient);
export const makeSearchPayable = () => new SearchPayableHandler(httpClient);
export const makeCreatePayable = () => new CreatePayableHandler(httpClient);
export const makePayPayable = () => new PayPayableHandler(httpClient);
export const makeGetCashFlow = () => new GetCashFlowHandler(httpClient);
export const makeCreateFinancialEntry = () => new CreateFinancialEntryHandler(httpClient);
export const makeSearchFinancialCategory = () => new SearchFinancialCategoryHandler(httpClient);
